# Generated by Django 4.2.29 on 2026-04-01 23:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavouritearticle',
            unique_together={('user', 'article')},
        ),
    ]
