version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_django
    restart: always
    environment:
      POSTGRES_DB: advanced_db
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
